# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "df4c2debc7cbe3c42fc2f5a4c1c8ef0ef9571b53"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.EasyMonad]]
deps = ["MacroTools", "MonadInterface"]
git-tree-sha1 = "251e368fe9379aef3c0eacf6c23a24be6104ffe3"
repo-rev = "main"
repo-url = "https://github.com/JuliaHybrid/EasyMonad.jl.git"
uuid = "e4dbf12b-b8cf-4673-b6eb-8b0d4667dd49"
version = "0.1.0"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.10"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MonadInterface]]
git-tree-sha1 = "7e4db9bbbae34fafd2e4a8784e9755d8524ba299"
repo-rev = "main"
repo-url = "https://github.com/JuliaHybrid/MonadInterface.jl.git"
uuid = "4c81018e-a0fd-4a0d-a53b-43c59f4db333"
version = "0.1.0"

[[deps.NestedVector]]
deps = ["EasyMonad", "MonadInterface"]
git-tree-sha1 = "72c74f8503843017b18bfa6cff1d4d7b5e1a3794"
repo-rev = "main"
repo-url = "https://github.com/overshiki/NestedVector.jl.git"
uuid = "03826054-d4ac-482b-9e88-e171687816a8"
version = "0.1.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.StringParser]]
deps = ["EasyMonad", "MonadInterface", "NestedVector"]
git-tree-sha1 = "e457a40ffb19d7f572f1b61890c6155a9fb68898"
repo-rev = "main"
repo-url = "https://github.com/overshiki/StringParser.jl.git"
uuid = "82027a8e-1502-4d66-bc09-336c403f5d02"
version = "0.1.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
