# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "cacae143d1d1100882855936f7a86e1af62befba"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.EasyMonad]]
deps = ["MacroTools"]
git-tree-sha1 = "884193dc4d8128f8a5d1991249b4de926dd0d87a"
repo-rev = "main"
repo-url = "https://github.com/overshiki/EasyMonad.jl.git"
uuid = "e4dbf12b-b8cf-4673-b6eb-8b0d4667dd49"
version = "0.1.0"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.10"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.NestedVector]]
deps = ["EasyMonad"]
git-tree-sha1 = "dcaae5eb6c430e69c270b85d0f89894ba23c2395"
repo-rev = "main"
repo-url = "https://github.com/overshiki/NestedVector.jl.git"
uuid = "03826054-d4ac-482b-9e88-e171687816a8"
version = "0.1.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
